name: payflow

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow
      POSTGRES_DB: payflow_order
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payflow"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
