// Package provider defines payment-service's abstraction over external
// payment providers. No provider-specific type (Paystack's JSON shapes
// included) may leak past this package — the application layer only
// ever sees the types defined here.
package provider

import (
	"context"
	"time"
)

// TransactionStatus is a provider transaction's status, translated
// from whatever the provider's own vocabulary is into PayFlow's own.
type TransactionStatus string

const (
	TransactionStatusSuccess   TransactionStatus = "success"
	TransactionStatusFailed    TransactionStatus = "failed"
	TransactionStatusAbandoned TransactionStatus = "abandoned"
)

// InitializeTransactionInput is what PayFlow passes to a provider to
// start a transaction. Reference is always generated by PayFlow, never
// left for the provider to generate — we need a value to key our own
// records on before the provider responds.
type InitializeTransactionInput struct {
	Email       string
	AmountMinor int64
	Currency    string
	Reference   string
	CallbackURL string
}

// InitializeTransactionResult is what a provider returns after
// starting a transaction.
type InitializeTransactionResult struct {
	AuthorizationURL string
	AccessCode       string
	Reference        string
}

// VerifyTransactionResult is what a provider returns when asked for a
// transaction's current status.
type VerifyTransactionResult struct {
	Reference   string
	Status      TransactionStatus
	AmountMinor int64
	Currency    string
	PaidAt      time.Time // zero value if not yet paid
}

// PaymentProvider is payment-service's abstraction over an external
// payment provider (Paystack, or any future provider). Implementations
// live under provider/<name>/ and must not expose their own
// request/response types through this interface.
type PaymentProvider interface {
	InitializeTransaction(ctx context.Context, input InitializeTransactionInput) (InitializeTransactionResult, error)
	VerifyTransaction(ctx context.Context, reference string) (VerifyTransactionResult, error)
}
