basePath: /
definitions:
  httpapi.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
info:
  contact: {}
  description: External-facing HTTP API for PayFlow. Translates client requests into
    internal gRPC calls.
  title: PayFlow API Gateway
  version: "0.1"
paths:
  /health:
    get:
      description: Reports whether the api-gateway process is up and serving requests.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpapi.HealthResponse'
      summary: Health check
      tags:
      - health
swagger: "2.0"
